<?php
require_once '.\vendor\autoload.php';

function makeYoutubePlaylist()
{
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://www.googleapis.com/youtube/v3/playlists?part=snippet%2Cstatus&key=[YOUR_API_KEY]');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"snippet\":{\"title\":\"Sample playlist created via API\",\"description\":\"This is a sample playlist description.\",\"tags\":[\"sample playlist\",\"API call\"],\"defaultLanguage\":\"en\"},\"status\":{\"privacyStatus\":\"private\"}}");
    curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

    $headers = array();
    $headers[] = 'Authorization: Bearer [YOUR_ACCESS_TOKEN]';
    $headers[] = 'Accept: application/json';
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);

}


function getAlbumArt($album)
{
    $apikey = 'e4a73d4b8778799519e84ff54d541c9b';
    $json = @file_get_contents("http://ws.audioscrobbler.com/2.0/?method=album.search&album=" . $album . "&api_key=" . $apikey . "&format=json");
    if ($json === FALSE) {
        echo '';
    } else {
        $decoded = json_decode($json, true);
        $art = array();
        if (array_key_exists(0, $decoded['results']['albummatches']['album'])) {

            $count = count($decoded['results']['albummatches']['album'][0]['image']) - 1;

            for ($i = 0; $i <= $count; $i++) {
                if (array_key_exists('image', $decoded['results']['albummatches']['album'][0])) {
                    array_push($art, $decoded['results']['albummatches']['album'][0]['image'][$i]['#text']);
                }
            }

            return $art;
        } else {
            echo '';
        }
    }
}

//$art = getAlbumArt('exodus');
//var_dump($art);


function getAlbumInfo($artist, $album)
{
    $apikey = 'e4a73d4b8778799519e84ff54d541c9b';
    $json = file_get_contents("http://ws.audioscrobbler.com/2.0/?method=album.getinfo&api_key=" . $apikey . "&artist=" . $artist . "&album=" . $album . "&format=json");
    $decoded = json_decode($json, true);

    //return $info
    return $decoded;

//$info = getAlbumInfo('nirvana', 'nevermind');
//var_dump($info['summary']);

}

function getArtistInfo($artist)
{
    $apikey = 'e4a73d4b8778799519e84ff54d541c9b';
    $json = file_get_contents("https://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist=" . $artist . "&api_key=" . $apikey . "&format=json");
    $decoded = json_decode($json, true);

    return $decoded;
}

function getYoutubePlaylistItems($playlistId)
{
    $apiKey = 'AIzaSyDDZ0qDH57y64Fg1dzYm-njzfE-1T9h2eU';
    $token = 'wwFYlWXg_uutD8t_XljXoU3oSeZwda4XMfPcxt9dzhaumq297qYXgso3euxmLwVjAaXIfQTZCW92h6-RI5EodiU';

    $maxResults = 50;

    $string = json_decode(file_get_contents('https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=' . $playlistId . '&maxResults=' . $maxResults . '&key=' . $apiKey . ''));

    $playlistSongs = array();
    foreach ($string->items as $item) {
        $playlistSongs[] = $item->snippet->title;
    }
    return $playlistSongs;
}

function getSpotifySongs($id)
{
    $token = 'BQBQtb5OGqrWD7W-m_XHmq1SqRPdfb6gWxbyRqMLOV9X1FioVH04hrpdBfiuLVeCM-LkNl0uy5BDWBiN8zNBUq3krDUXz0Ox0-Ti4RngKM8OKWotJp7emJ4VFdWC1hhfNvXZzGSeV0-Hjl81bYhAjokJeIJ1nkb5Vhy8TpDp3fkCMAe85ny5zGfd1ESWRde8g36zwcPs-c6q6zBPb68nDdWvoOGLh7MbpU6PiB8KAhwI41hqpF6KWNvJFK_dKjKgOXvHGkujXBsNu6zF-l1M5Etp-XFgww';
    $url = 'https://api.spotify.com/v1/playlists/' . $id . '/tracks';
    $ch = curl_init($url);
    $customHeaders = array(
        'Accept: application/json',
        'Content-Type: application/json',
        'Authorization: Bearer ' . $token
    );
    curl_setopt($ch, CURLOPT_HTTPHEADER, $customHeaders);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    $result = json_decode(curl_exec($ch), true);

    return $result;
}


function getPlaylistInfo($playlistId)
{
    $youtube = new Madcoda\Youtube(array('key' => 'AIzaSyDDZ0qDH57y64Fg1dzYm-njzfE-1T9h2eU'));
    $playlistItems = $youtube->getPlaylistItemsByPlaylistId($playlistId);

    $decoded = json_decode(json_encode($playlistItems), true);
    $titles = array();
    foreach ($decoded as  $songName) {
        $titles[] = $songName['snippet']['title'];
    }
    return$titles;
}

//$playlistId = 'PLzVlnTZP79inLqTXa-WSZ6uZjrr5hdv1P';
//$playlistSongs = getPlaylistInfo($playlistId);//gets song names form yt
//var_dump($playlistSongs);

?>

